apiVersion: platform.myorg.io/v1alpha1
kind: Tenant
metadata:
  name: example-tenant
  namespace: default
spec:
  owner: "harsha@email"
  namespaceName: team-a-namespace
  resourceQuota:
    cpu: "2"
    memory: 4Gi
    pods: 10
  limitRange:
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    defaultLimit:
      cpu: 500m
      memory: 1Gi
  networkPolicy:
    allowNamespaces:
      - default
      - team-a-namespace
    denyExternal: true
  rbac:
    adminUsers:
      - admin1
      - admin2
    viewerUsers:
      - viewer1
  policy:
    enforceRegistry: myregistry.example.com
    allowPrivileged: false
  monitoring:
    enable: true
    labels:
      environment: dev
